# Generated by Django 5.1 on 2024-09-02 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_analysis_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='analyzer',
            field=models.CharField(default='exit', max_length=50),
            preserve_default=False,
        ),
    ]
